export const MAP_API_KEY = 'AIzaSyDftL7_-h646eFDzibvnspGk4V1OmsAsCA';
 export const FS_CLIENT_ID = 'NNGXP0NVZGYQRAIRQQECM1KNJZ2ERDHH2SGZXXB1REA2MIOU';
 export const FS_CLIENT_SECRET = 'OU0MV2ROYVJ5NWYX1PGYO2KRAO5QA25VKZBSKSI4SBNRIUI1';
