export const MAP_API_KEY = 'AIzaSyDftL7_-h646eFDzibvnspGk4V1OmsAsCA';

export const FS_CLIENT_ID = 'AEC4SIVMT34PQ5PMKLVGTE3ZEZUZ5O52W0LSEHKPUJCS4LXL';

export const FS_CLIENT_SECRET = 'BKIQLYWDNFOOTAV2VHP3SZW33DW3NIHRQMLHYJM0YRJKIKK2';
